module unitree_go {
  module msg {
    module dds_ {
      struct PathPoint_ {
        float t_from_start;
        float x;
        float y;
        float yaw;
        float vx;
        float vy;
        float vyaw;
      };
    };
  };
};
