module unitree_hg {
  module msg {
    module dds_ {
      struct MotorCmd_ {
        uint8 mode;
        float q;
        float dq;
        float tau;
        float kp;
        float kd;
        uint32 reserve;
      };
    };
  };
};
